/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.digitalasset.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.digitalasset.ledger.api.v1.{value=>$u0020rpcvalue}
package com.digitalasset.quickstart.iou.model {
  package Main {
    final case class Sign(signer: ` lfdomainapi`.Primitive.Party) extends ` lfdomainapi`.ValueRef

    object Sign extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.Party, _root_.com.digitalasset.quickstart.iou.model.Main.Sign] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val signer: ` C`[` lfdomainapi`.Primitive.Party];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val signer = ` f`(` view`.signer)
          };
          new $anon()
        }
      };
      implicit val `Sign Value`: ` lfdomainapi`.Value[_root_.com.digitalasset.quickstart.iou.model.Main.Sign] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.digitalasset.quickstart.iou.model.Main.Sign] {
          override def write(value: _root_.com.digitalasset.quickstart.iou.model.Main.Sign): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("signer", ` lfdomainapi`.Value.encode(value.signer)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.digitalasset.quickstart.iou.model.Main.Sign] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "signer"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv0) match {
                case _root_.scala.Some(signer) => Some(Sign(signer))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.Main, "Main", "Sign");
      implicit def `Sign LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.digitalasset.quickstart.iou.model.Main.Sign] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.digitalasset.quickstart.iou.model.Main.Sign] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.digitalasset.quickstart.iou.model.Main.Sign] = {
            object `view ` extends view[lte.Field] {
              val signer = lte.field("signer", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.digitalasset.quickstart.iou.model.Main.Sign] = lte.RecordFields.xmapN(lte.fields(`view `.signer))({
                case signer => _root_.com.digitalasset.quickstart.iou.model.Main.Sign(signer)
              })({
                case _root_.com.digitalasset.quickstart.iou.model.Main.Sign(signer) => signer
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
